## Dynamic

- type: latheRecipePack
  id: ServiceStatic
  recipes:
  - Bucket
  - Ashtray
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - SprayBottle
  - TrashBag
  - LightReplacer
  - MopItem
  - Holoprojector
  - WetFloorSign
  - WireBrush

- type: latheRecipePack
  id: ServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - UniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - SmartFridgeCircuitboard
  - PrinterDocMachineCircuitboard # DS-14
  - SmartFridgeCircuitboard

- type: latheRecipePack
  id: Botany
  recipes:
  - HydroponicsToolMiniHoe
  - HydroponicsToolHatchet
  - HydroponicsToolScythe
  - HydroponicsToolClippers
  - ClothingBeltPlant
  - PlantBag

- type: latheRecipePack
  id: Janitor
  recipes:
  - TrashBag # Backmen
  - AdvMopItem
  - WeaponSprayNozzle
  - ClothingBackpackWaterTank
  - MegaSprayBottle

- type: latheRecipePack
  id: Instruments
  recipes:
  - SynthesizerInstrument
  - PushHorn

- type: latheRecipePack
  id: ServiceBoards
  recipes:
  - BiofabricatorMachineCircuitboard
  - FatExtractorMachineCircuitboard
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
  # Erida-start
  - HydroponicsTrayMachineCircuitboard
  - SeedExtractorMachineCircuitboard
  # Erida-end
